root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -buildvcs=false -o server ."
  bin = "server"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor"]
[log]
  color = "true"
  time = "true"
[serve]
  cmd = "./server"
  delay = 1000
[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
[watch]
  dirs = ["."]